### ISSUE TITLE
The low performance on the NYT dataset (partial match)

### ISSUE THREAD

**Issue by vhientran** [BDBC-KG-NLP/Recurrent_Interaction_Network_EMNLP2020#1]
Hi @sunkaikai ,

Thank you very much for releasing the source code. I have tried to train and evaluate on the NYT (partial match), but I only got the best performance on NYT is: 83.21% (F1-score) in the case of partial match. Meanwhile, the reported best result on NYT by RIN model is: 87.3% (in Table 1). I wonder what should I do for getting this performance. Thanks so much!
Also, I would like to attach the file logs.txt .

**epoch	train_loss	train_loss_er	train_loss_rc	dev_loss	dev_loss_er	dev_loss_rc	P	R	F1**
1	73.2485	3.4390	69.8095	4.2972	2.2674	2.0298	0.8443	0.7026	0.7669
new best model saved at epoch 1: 73.2485	4.2972	0.8443	0.7026	0.7669
2	3.5344	1.9053	1.6291	3.7588	1.9997	1.7591	0.8486	0.7773	0.8114
new best model saved at epoch 2: 3.5344	3.7588	0.8486	0.7773	0.8114
3	2.4777	1.3386	1.1390	3.9806	2.0999	1.8807	0.8106	0.8226	0.8165
new best model saved at epoch 3: 2.4777	3.9806	0.8106	0.8226	0.8165
4	1.7885	0.9412	0.8473	4.1865	2.3059	1.8806	0.8253	0.8176	0.8214
new best model saved at epoch 4: 1.7885	4.1865	0.8253	0.8176	0.8214
5	1.3211	0.6723	0.6488	4.5396	2.5449	1.9946	0.8277	0.8180	0.8228
new best model saved at epoch 5: 1.3211	4.5396	0.8277	0.8180	0.8228
6	1.0103	0.4998	0.5105	5.0407	2.9166	2.1241	0.8392	0.8148	0.8268
new best model saved at epoch 6: 1.0103	5.0407	0.8392	0.8148	0.8268
7	0.7966	0.3867	0.4099	5.7944	3.4451	2.3494	0.8210	0.8221	0.8215
8	0.6689	0.3082	0.3608	5.9889	3.4514	2.5374	0.8069	0.8313	0.8189
9	0.5905	0.2657	0.3248	6.5597	3.8226	2.7371	0.7920	0.8497	0.8198
10	0.5239	0.2350	0.2889	6.0840	3.4209	2.6631	0.8172	0.8354	0.8262
11	0.4712	0.2044	0.2668	6.1135	3.5208	2.5926	0.8488	0.8160	0.8321
**new best model saved at epoch 11: 0.4712	6.1135	0.8488	0.8160	0.8321**
12	0.4310	0.1831	0.2479	6.5186	3.8178	2.7008	0.8271	0.8260	0.8266
13	0.4003	0.1692	0.2311	6.3287	3.6748	2.6539	0.8086	0.8508	0.8292
14	0.3760	0.1589	0.2171	7.1753	4.0607	3.1147	0.8109	0.8297	0.8202
15	0.3468	0.1429	0.2039	6.8977	4.0689	2.8288	0.8203	0.8353	0.8277
16	0.3426	0.1379	0.2047	7.5494	4.3998	3.1496	0.8261	0.8231	0.8246
17	0.3212	0.1318	0.1894	7.4385	4.3242	3.1143	0.8026	0.8457	0.8236
18	0.2987	0.1161	0.1825	7.8317	4.3870	3.4447	0.8174	0.8224	0.8199
19	0.3014	0.1221	0.1793	7.1426	4.0276	3.1150	0.8094	0.8374	0.8232
20	0.2867	0.1129	0.1737	7.4272	4.2601	3.1672	0.8333	0.8196	0.8264
21	0.2729	0.1090	0.1639	7.3648	4.0702	3.2946	0.8269	0.8195	0.8232
22	0.2703	0.1062	0.1641	7.2367	4.1408	3.0958	0.8467	0.8111	0.8285
23	0.2564	0.0998	0.1566	8.1523	4.6444	3.5079	0.8174	0.8248	0.8211
24	0.2298	0.0887	0.1412	7.9464	4.5360	3.4104	0.8135	0.8271	0.8202
25	0.2450	0.0950	0.1500	7.3765	4.1272	3.2493	0.8188	0.8253	0.8220
26	0.2355	0.0905	0.1450	7.4168	4.3299	3.0869	0.8139	0.8295	0.8216
27	0.2237	0.0869	0.1368	7.8651	4.5665	3.2986	0.8275	0.8228	0.8252
28	0.2149	0.0828	0.1321	7.5777	4.1679	3.4098	0.8349	0.8289	0.8319
29	0.2124	0.0796	0.1329	8.1536	4.6870	3.4666	0.8180	0.8178	0.8179
30	0.2151	0.0788	0.1362	7.4739	4.3265	3.1474	0.8316	0.8208	0.8262
31	0.2076	0.0782	0.1294	8.1315	4.6649	3.4666	0.8311	0.8170	0.8240
32	0.2001	0.0716	0.1284	7.8508	4.4605	3.3903	0.8427	0.8091	0.8256
33	0.2030	0.0755	0.1275	7.7402	4.3821	3.3582	0.8404	0.7942	0.8167
34	0.1971	0.0735	0.1236	8.1181	4.6893	3.4288	0.8269	0.8213	0.8241
35	0.1926	0.0713	0.1213	8.9690	4.9311	4.0379	0.8262	0.8091	0.8176
36	0.1890	0.0676	0.1215	8.4963	4.8067	3.6896	0.8059	0.8330	0.8193
37	0.1917	0.0681	0.1235	8.3412	4.6584	3.6828	0.8324	0.7984	0.8150
38	0.1897	0.0686	0.1211	8.6424	4.8544	3.7880	0.8371	0.8059	0.8212
39	0.1779	0.0648	0.1131	8.4247	4.6384	3.7863	0.8403	0.8033	0.8214
40	0.1863	0.0669	0.1194	8.2358	4.6130	3.6228	0.8288	0.8109	0.8197

**Comment by sunkaikai** [comment]
@angelotran05 
Sorry! There was a bug in the previous code. Just fixed it.
This is the log.txt by running the new code.

Prec: 0.7290, Recall: 0.6751, F1: 0.7010
New best model saved!
Prec: 0.7769, Recall: 0.7456, F1: 0.7610
New best model saved!
Prec: 0.8027, Recall: 0.7683, F1: 0.7851
New best model saved!
Prec: 0.8110, Recall: 0.8041, F1: 0.8075
New best model saved!
Prec: 0.8191, Recall: 0.8144, F1: 0.8167
New best model saved!
Prec: 0.8412, Recall: 0.8105, F1: 0.8255
New best model saved!
Prec: 0.8443, Recall: 0.8208, F1: 0.8324
New best model saved!
Prec: 0.8333, Recall: 0.8427, F1: 0.8380
New best model saved!
Prec: 0.8422, Recall: 0.8420, F1: 0.8421
New best model saved!
Prec: 0.8342, Recall: 0.8530, F1: 0.8435
New best model saved!
Prec: 0.8505, Recall: 0.8401, F1: 0.8452
New best model saved!
Prec: 0.8474, Recall: 0.8531, F1: 0.8503
New best model saved!
Prec: 0.8524, Recall: 0.8509, F1: 0.8517
New best model saved!
Prec: 0.8453, Recall: 0.8597, F1: 0.8524
New best model saved!
Prec: 0.8514, Recall: 0.8522, F1: 0.8518
Prec: 0.8547, Recall: 0.8607, F1: 0.8577
New best model saved!
Prec: 0.8665, Recall: 0.8534, F1: 0.8599
New best model saved!
Prec: 0.8424, Recall: 0.8651, F1: 0.8536
Prec: 0.8607, Recall: 0.8549, F1: 0.8578
Prec: 0.8448, Recall: 0.8684, F1: 0.8564
Prec: 0.8658, Recall: 0.8568, F1: 0.8613
New best model saved!
Prec: 0.8513, Recall: 0.8741, F1: 0.8626
New best model saved!
Prec: 0.8438, Recall: 0.8777, F1: 0.8604
Prec: 0.8652, Recall: 0.8614, F1: 0.8633
New best model saved!
Prec: 0.8550, Recall: 0.8716, F1: 0.8632
Prec: 0.8674, Recall: 0.8614, F1: 0.8644
New best model saved!
Prec: 0.8630, Recall: 0.8670, F1: 0.8650
New best model saved!
Prec: 0.8645, Recall: 0.8704, F1: 0.8675
New best model saved!
Prec: 0.8615, Recall: 0.8687, F1: 0.8651
Prec: 0.8531, Recall: 0.8776, F1: 0.8651
Prec: 0.8576, Recall: 0.8748, F1: 0.8661
Prec: 0.8536, Recall: 0.8740, F1: 0.8637
Prec: 0.8599, Recall: 0.8745, F1: 0.8672
Prec: 0.8569, Recall: 0.8727, F1: 0.8648
Prec: 0.8415, Recall: 0.8825, F1: 0.8615
Prec: 0.8741, Recall: 0.8571, F1: 0.8655
Prec: 0.8624, Recall: 0.8693, F1: 0.8658
Prec: 0.8450, Recall: 0.8825, F1: 0.8633
Prec: 0.8644, Recall: 0.8800, F1: 0.8721
New best model saved!
Prec: 0.8503, Recall: 0.8819, F1: 0.8658
Prec: 0.8642, Recall: 0.8697, F1: 0.8669
Prec: 0.8621, Recall: 0.8729, F1: 0.8675
Prec: 0.8484, Recall: 0.8862, F1: 0.8669
Prec: 0.8462, Recall: 0.8845, F1: 0.8649
Prec: 0.8442, Recall: 0.8858, F1: 0.8645
Prec: 0.8527, Recall: 0.8838, F1: 0.8680
Prec: 0.8425, Recall: 0.8868, F1: 0.8641
Prec: 0.8465, Recall: 0.8838, F1: 0.8648
Prec: 0.8445, Recall: 0.8825, F1: 0.8631
Prec: 0.8416, Recall: 0.8861, F1: 0.8632
Prec: 0.8490, Recall: 0.8873, F1: 0.8677
Prec: 0.8521, Recall: 0.8858, F1: 0.8686
Prec: 0.8591, Recall: 0.8867, F1: 0.8727
New best model saved!
Prec: 0.8495, Recall: 0.8826, F1: 0.8657
Prec: 0.8487, Recall: 0.8877, F1: 0.8678
Prec: 0.8510, Recall: 0.8824, F1: 0.8664
Prec: 0.8398, Recall: 0.8901, F1: 0.8642
Prec: 0.8530, Recall: 0.8815, F1: 0.8670
Prec: 0.8505, Recall: 0.8840, F1: 0.8669
Prec: 0.8575, Recall: 0.8825, F1: 0.8698
Prec: 0.8380, Recall: 0.8956, F1: 0.8658
Prec: 0.8520, Recall: 0.8875, F1: 0.8694
Prec: 0.8448, Recall: 0.8931, F1: 0.8683
Prec: 0.8609, Recall: 0.8855, F1: 0.8730
New best model saved!
Prec: 0.8421, Recall: 0.8855, F1: 0.8633
Prec: 0.8523, Recall: 0.8852, F1: 0.8684
Prec: 0.8460, Recall: 0.8945, F1: 0.8696
Prec: 0.8529, Recall: 0.8867, F1: 0.8695
Prec: 0.8392, Recall: 0.8887, F1: 0.8632
Prec: 0.8549, Recall: 0.8778, F1: 0.8662
Prec: 0.8343, Recall: 0.8945, F1: 0.8633
Prec: 0.8359, Recall: 0.8930, F1: 0.8635
Prec: 0.8585, Recall: 0.8795, F1: 0.8689
Prec: 0.8431, Recall: 0.8901, F1: 0.8660
Prec: 0.8490, Recall: 0.8857, F1: 0.8669
Prec: 0.8636, Recall: 0.8793, F1: 0.8714
Prec: 0.8608, Recall: 0.8825, F1: 0.8715
Prec: 0.8507, Recall: 0.8836, F1: 0.8668

**Comment by vhientran** [comment]
Thank you!
